// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import dotenv from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

dotenv.config({
  path: path.resolve(import.meta.dirname, "../../.env") 
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` does not connect to the database, so allow it to run
    // during installs and frontend-only CI builds where DATABASE_URL is absent.
    // Commands that use the database still require a valid URL, and the runtime
    // client validates it separately in src/client.ts.
    url: process.env.DATABASE_URL ?? "",
  },
});
